In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [44]:
df = pd.read_csv(r"C:\Users\personal\Downloads\phone.csv")
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [45]:
df.tail()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[5 rows x 21 columns]

In [46]:
df.isna().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [47]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [48]:
sns.set_style('darkgrid')

In [49]:
sns.pairplot(df, height=10, aspect=0.6)

## Spliting of the dataset to Train and Test

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
x = df.drop('price_range', axis='columns')

In [53]:
y = df['price_range']

In [54]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [55]:
x_train.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
1619           1641     0          1.1         0   6       0          48   
1806            628     1          1.8         0   5       0          60   
295            1162     0          2.0         0   0       1          56   
1386            610     1          1.6         1   9       0          52   
1190           1092     1          0.5         1  10       0          11   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
1619    0.7         97        8   7        224      1994  1695    13     6   
1806    0.2         87        6   6       1047      1534  1337    12     7   
295     0.7        114        7   1         56       997  1652     5     0   
1386    0.4         90        4  19       1039      1273  3472    10     4   
1190    0.5        167        3  14        468       571   737    14     4   

      talk_time  three_g  touch_screen  wifi  
1619         17        1             0     1  
1806         14        0             1     0  
295          20        1             0     0  
1386         12        1             1     1  
1190         11        0             1     0

In [56]:
len(x_test)

400

## Decision Tree Classifier

In [57]:
from sklearn import tree

In [58]:
model = tree.DecisionTreeClassifier()

In [59]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [60]:
model.score(x_test,y_test)

0.855

In [61]:
model.score(x_train,y_train)

1.0

In [62]:
model.predict([[1594,586,1,0.6,0,16,1,42,0.3,121,7,17,785,1118,1869,12,2,7,1,1]])

C:\Users\personal\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

##  Random Forest Classifier

In [63]:
from sklearn.ensemble import RandomForestClassifier

In [64]:
model = RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [65]:
model.score(x_test,y_test)

0.875

In [66]:
model.predict([[1594,586,1,0.6,0,16,1,42,0.3,121,7,17,785,1118,1869,12,2,7,1,1]])

C:\Users\personal\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

##  Support Vector Machine

In [67]:
from sklearn.svm import SVC

In [68]:
model = SVC()


In [69]:
model.fit(x_train,y_train)

SVC()

In [70]:
model.score(x_test,y_test)

0.955

In [71]:
model.predict([[1594,586,1,0.6,0,16,42,0.3,121,7,17,785,1118,1869,12,2,7,1,1,1]])

C:\Users\personal\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

##  Logistic Regression


In [72]:
from sklearn.linear_model import LogisticRegression

In [73]:
model = LogisticRegression()
model.fit(x_train,y_train)

C:\Users\personal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [74]:
model.score(x_test,y_test)

0.6475

In [75]:
model.predict([[1594,586,1,0.6,0,16,42,0.3,121,7,17,785,1118,1869,12,2,7,1,1,1]])

C:\Users\personal\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

##  K-Nearest Neighbors (KNN) Classifier

In [76]:
from sklearn.neighbors import KNeighborsClassifier

In [77]:
model = KNeighborsClassifier()

In [78]:
model.fit(x_train,y_train)

KNeighborsClassifier()

In [79]:
model.score(x_test,y_test)

C:\Users\personal\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9275

In [80]:
model.predict([[1594,586,1,0.6,0,16,42,0.3,121,7,17,785,1118,1869,12,2,7,1,1,1]])

C:\Users\personal\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
C:\Users\personal\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([2], dtype=int64)

##### Support Vector Machine is the best Model for carrying this Prediction as it's accuracy is 0.95

In [81]:
model.predict([[1594,586,1,0.6,0,16,42,0.3,121,7,17,785,1118,1869,12,2,7,1,1,1]])

C:\Users\personal\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
C:\Users\personal\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([2], dtype=int64)